# Numpy

In [1]:
import numpy as np
import pandas as pd

In [2]:
data  = np.random.rand(20)
data

array([0.16035291, 0.28046137, 0.80267374, 0.17818557, 0.16576872,
       0.86037922, 0.63952371, 0.74417732, 0.75187699, 0.61902794,
       0.43328699, 0.03725637, 0.26866143, 0.27958169, 0.64393405,
       0.84703158, 0.82202824, 0.37855636, 0.16489046, 0.84954879])

In [3]:
data.dtype

dtype('float64')

In [4]:
data.shape

(20,)

In [5]:
data.size

20

In [6]:
len(data[ data > 0.5] )
(data[ data > 0.5] )

array([0.80267374, 0.86037922, 0.63952371, 0.74417732, 0.75187699,
       0.61902794, 0.64393405, 0.84703158, 0.82202824, 0.84954879])

In [7]:
numpydata2D  = np.random.rand(10,3)
numpydata2D

array([[0.33400281, 0.56602063, 0.91705256],
       [0.66329161, 0.60795667, 0.84533688],
       [0.13194888, 0.81342462, 0.67554881],
       [0.21043528, 0.81759514, 0.53615887],
       [0.98324273, 0.42589865, 0.13597834],
       [0.67940776, 0.78089276, 0.14209655],
       [0.38450655, 0.17778399, 0.81369252],
       [0.58639568, 0.70311686, 0.53555039],
       [0.68361017, 0.76986898, 0.97088463],
       [0.296718  , 0.7897508 , 0.38490433]])

In [8]:
date = pd.date_range('today', periods = 10)
columns = list('ABC')
rows = list('abcdefghij')
dff = pd.DataFrame(numpydata2D, columns = columns, index=rows)
dff

A         B         C
a  0.334003  0.566021  0.917053
b  0.663292  0.607957  0.845337
c  0.131949  0.813425  0.675549
d  0.210435  0.817595  0.536159
e  0.983243  0.425899  0.135978
f  0.679408  0.780893  0.142097
g  0.384507  0.177784  0.813693
h  0.586396  0.703117  0.535550
i  0.683610  0.769869  0.970885
j  0.296718  0.789751  0.384904

In [9]:
zero = np.zeros((2,6))
zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
once = np.ones((1,3))
once

array([[1., 1., 1.]])

In [11]:
lst = np.arange(1,10)
lst

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
lst = lst.reshape(3,3)
arr = lst.copy() 
lst

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
lst = lst.ravel()
lst

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
l1 = [1,2,3,4,5,6,7,1,0]
nparr = np.array(l1)
nparr

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [15]:
nparr.ndim

1

In [16]:
nparr.size

9

In [17]:
nparr.argmax()

6

In [18]:
nparr.argmin()

8

In [19]:
nparr.argsort()

array([8, 0, 7, 1, 2, 3, 4, 5, 6], dtype=int64)

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
lst = [[1,2,3], [3,2,6], [7,5,0]]
lst

[[1, 2, 3], [3, 2, 6], [7, 5, 0]]

In [27]:
nparr = np.array(lst)
nparr

array([[1, 2, 3],
       [3, 2, 6],
       [7, 5, 0]])

In [28]:
nparr.argmax()

6

In [29]:
nparr.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [30]:
nparr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [31]:
nparr.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0]], dtype=int64)

In [32]:
nparr.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]], dtype=int64)

In [33]:
nparr.argsort(axis=1)

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0]], dtype=int64)

In [37]:
nparr.max()

7

In [38]:
nparr.min()

0

In [39]:
nparr.all()

False

In [46]:
lst = [1,2,3]
ar = np.array(lst)
ar.all()

True